# Generated by Django 5.2.8 on 2025-11-06 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_type', models.CharField(choices=[('assistance', 'Language Learning Assistance'), ('quiz', 'Quiz Chat'), ('matching', 'Matching Chat')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('total_sessions', models.IntegerField(default=0)),
                ('quiz_score_avg', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('achievements', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('user', 'chat_type')},
            },
        ),
    ]
